global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]
  - job_name: 'worker-service-metrics'
    # For Docker Desktop (macOS/Windows WSL2), use host.docker.internal
    # For Linux, if worker binds to 0.0.0.0, you might access directly or via specific host IP
    static_configs:
      - targets: ['host.docker.internal:9091'] # Assuming worker exposes on 9091